CREATE TABLE APP.ACCOUNT
(
   ACCOUNT_ID                VARCHAR(8)      NOT NULL,
   BALANCE                   DECIMAL(10,2),
   BEGIN_BALANCE             DECIMAL(10,2),
   BEGIN_BALANCE_TIME_STAMP  BLOB            NOT NULL,
   CREDIT_LINE               DECIMAL(10,2),
   DESCRIPTION               VARCHAR(30),
   TYPE                      VARCHAR(24)
);

ALTER TABLE APP.ACCOUNT
   ADD CONSTRAINT SQL151101194313900
   PRIMARY KEY (ACCOUNT_ID);

CREATE TABLE APP.ADDRESS
(
   ID         INTEGER        NOT NULL,
   ADDRESS1   VARCHAR(255),
   ADDRESS2   VARCHAR(255),
   COUNTY     VARCHAR(255),
   POSTCODE   VARCHAR(255),
   TOWN       VARCHAR(255),
   COUNTRYID  INTEGER,
   REGIONID   INTEGER
);

ALTER TABLE APP.ADDRESS
   ADD CONSTRAINT SQL151101194315260
   PRIMARY KEY (ID);

CREATE INDEX APP.SQL151101194341070
   ON APP.ADDRESS (REGIONID ASC);

CREATE INDEX APP.SQL151101194340710
   ON APP.ADDRESS (COUNTRYID ASC);


CREATE TABLE APP.ALLOWABLEENTITYASSETTYPE
(
   ASSETTYPEID    INTEGER   NOT NULL,
   ASSETENTITYID  INTEGER   NOT NULL
);

ALTER TABLE APP.ALLOWABLEENTITYASSETTYPE
   ADD CONSTRAINT SQL151101194334570
   PRIMARY KEY (ASSETTYPEID, ASSETENTITYID);

CREATE INDEX APP.SQL151101194400070
   ON APP.ALLOWABLEENTITYASSETTYPE (ASSETTYPEID ASC);

CREATE INDEX APP.SQL151101194359800
   ON APP.ALLOWABLEENTITYASSETTYPE (ASSETENTITYID ASC);


CREATE TABLE APP.ASSET
(
   ID                             INTEGER        NOT NULL,
   ADVANCEDVIEWING                SMALLINT,
   AGREEMENTTYPEID                INTEGER,
   ALLOWFEEDBACK                  SMALLINT,
   AUTHOR                         VARCHAR(255),
   AWAITINGTHUMBNAILREGENERATION  SMALLINT,
   BULKUPLOADTIMESTAMP            TIMESTAMP,
   CANEMBEDFILE                   SMALLINT,
   CODE                           VARCHAR(255),
   DATEADDED                      TIMESTAMP,
   DATEFIRSTAPPROVED              TIMESTAMP,
   DATELASTMODIFIED               TIMESTAMP,
   DATESUBMITTED                  TIMESTAMP,
   EMBEDDEDPREVIEWCLIPLOCATION    VARCHAR(255),
   EXPIRYDATE                     TIMESTAMP,
   FILECHECKOUTTIME               TIMESTAMP,
   FILELOCATION                   VARCHAR(255),
   FILESIZEINBYTES                BIGINT,
   HASWORKINGFILE                 SMALLINT,
   IMPORTEDASSETID                VARCHAR(255),
   ISBRANDTEMPLATE                SMALLINT,
   ISNOTDUPLICATE                 SMALLINT,
   ISPREVIEWRESTRICTED            SMALLINT,
   ISSENSITIVE                    SMALLINT,
   ISUNSUBMITTED                  SMALLINT,
   LASTDOWNLOADED                 TIMESTAMP,
   MEDIUMFILELOCATION             VARCHAR(255),
   NUMDOWNLOADS                   INTEGER,
   NUMVIEWS                       INTEGER,
   ORIGINALFILELOCATION           VARCHAR(255),
   ORIGINALFILENAME               VARCHAR(255),
   PRICE                          INTEGER,
   SMALLFILELOCATION              VARCHAR(255),
   THUMBNAILFILELOCATION          VARCHAR(255),
   THUMBNAILGENERATIONFAILED      SMALLINT,
   UPLOADEDTHUMBNAILFILE          VARCHAR(255),
   VERSIONNUMBER                  INTEGER,
   ADDEDBYUSERID                  INTEGER,
   ASSETENTITYID                  INTEGER,
   ASSETTYPEID                    INTEGER,
   CURRENTVERSIONID               INTEGER,
   FILECHECKEDOUTBYUSERID         INTEGER,
   FILEFORMATID                   INTEGER,
   LASTMODIFIEDBYUSERID           INTEGER,
   SUBMITTEDBYUSERID              INTEGER
);

ALTER TABLE APP.ASSET
   ADD CONSTRAINT SQL151101194326030
   PRIMARY KEY (ID);

CREATE INDEX APP.SQL151101194347740
   ON APP.ASSET (ASSETENTITYID ASC);

CREATE INDEX APP.SQL151101194347890
   ON APP.ASSET (CURRENTVERSIONID ASC);

CREATE INDEX APP.SQL151101194349640
   ON APP.ASSET (SUBMITTEDBYUSERID ASC);

CREATE INDEX APP.SQL151101194349000
   ON APP.ASSET (LASTMODIFIEDBYUSERID ASC);

CREATE INDEX APP.SQL151101194348580
   ON APP.ASSET (FILEFORMATID ASC);

CREATE INDEX APP.SQL151101194349360
   ON APP.ASSET (ADDEDBYUSERID ASC);

CREATE INDEX APP.SQL151101194348180
   ON APP.ASSET (ASSETTYPEID ASC);

CREATE INDEX APP.SQL151101194348820
   ON APP.ASSET (FILECHECKEDOUTBYUSERID ASC);


CREATE TABLE APP.ASSETBANKUSER
(
   ID                            INTEGER        NOT NULL,
   ADDITIONALAPPROVALNAME        VARCHAR(255),
   ADDRESS                       VARCHAR(255),
   ADMINNOTES                    VARCHAR(255),
   CANBECATEGORYADMIN            SMALLINT,
   CANLOGINFROMCMS               SMALLINT,
   CN                            VARCHAR(255),
   CONTENTALERTSUBSCRIBER        SMALLINT,
   DATECHANGEDPASSWORD           TIMESTAMP,
   DATELASTLOGGEDIN              TIMESTAMP,
   DATELASTMODIFIED              TIMESTAMP,
   DISPLAYNAME                   VARCHAR(255),
   DISTINGUISHEDNAME             VARCHAR(255),
   EMAILADDRESS                  VARCHAR(255),
   EXPIRYDATE                    TIMESTAMP,
   FORENAME                      VARCHAR(255),
   HASEVERLOGGEDIN               SMALLINT,
   HIDDEN                        SMALLINT,
   HOMEPAGEACCESSLEVELSEXPANDED  SMALLINT,
   HOMEPAGECATEGORIESEXPANDED    SMALLINT,
   ISADMIN                       SMALLINT,
   ISDELETED                     SMALLINT,
   ISSUSPENDED                   SMALLINT,
   JOBTITLE                      VARCHAR(255),
   LDAPSERVERINDEX               SMALLINT,
   MAILBOX                       VARCHAR(255),
   NOTACTIVEDIRECTORY            SMALLINT,
   NOTAPPROVED                   SMALLINT,
   ORGANISATION                  VARCHAR(255),
   PASSWORD                      VARCHAR(255),
   REACTIVATIONPENDING           SMALLINT,
   RECEIVEALERTS                 SMALLINT,
   REGISTERDATE                  TIMESTAMP,
   REGISTRATIONINFO              VARCHAR(255),
   REQUESTFULFILLER              SMALLINT,
   REQUIRESUPDATE                SMALLINT,
   SEARCHRESULTSPERPAGE          INTEGER,
   SURNAME                       VARCHAR(255),
   TITLE                         VARCHAR(255),
   USERNAME                      VARCHAR(255),
   VATNUMBER                     VARCHAR(255),
   ADDRESSID                     INTEGER,
   DIVISIONID                    INTEGER,
   INVITEDBYUSERID               INTEGER,
   LANGUAGEID                    INTEGER,
   LASTMODIFIEDBYID              INTEGER,
   REQUESTEDORGUNITID            INTEGER
);

ALTER TABLE APP.ASSETBANKUSER
   ADD CONSTRAINT SQL151101194324420
   PRIMARY KEY (ID);

CREATE INDEX APP.SQL151101194346770
   ON APP.ASSETBANKUSER (REQUESTEDORGUNITID ASC);

CREATE INDEX APP.SQL151101194346430
   ON APP.ASSETBANKUSER (DIVISIONID ASC);

CREATE INDEX APP.SQL151101194347000
   ON APP.ASSETBANKUSER (ADDRESSID ASC);

CREATE INDEX APP.SQL151101194346160
   ON APP.ASSETBANKUSER (INVITEDBYUSERID ASC);

CREATE INDEX APP.SQL151101194347180
   ON APP.ASSETBANKUSER (LASTMODIFIEDBYID ASC);

CREATE INDEX APP.SQL151101194346600
   ON APP.ASSETBANKUSER (LANGUAGEID ASC);


CREATE TABLE APP.ASSETENTITY
(
   ID                          INTEGER        NOT NULL,
   CANCOPYASSETS               SMALLINT,
   CANDOWNLOADCHILDREN         SMALLINT,
   DEFAULTCATEGORYID           INTEGER,
   EXCLUDEDFILEFORMATS         VARCHAR(255),
   INCLUDEDFILEFORMATS         VARCHAR(255),
   ISARTICLE                   SMALLINT,
   ISCATEGORYEXTENSION         SMALLINT,
   ISQUICKSEARCHABLE           SMALLINT,
   ISSEARCHABLE                SMALLINT,
   MUSTHAVEPARENT              SMALLINT,
   NAME                        VARCHAR(255),
   ONLYALLOWDEFAULTCATEGORY    SMALLINT,
   RESTAGREEMENTID             INTEGER,
   SEQUENCENUMBER              INTEGER,
   SHOWATTRIBUTELABELS         SMALLINT,
   SHOWONDESCENDANTCATEGORIES  SMALLINT,
   TERMFORSIBLING              VARCHAR(255),
   TERMFORSIBLINGS             VARCHAR(255),
   THUMBNAILFILENAME           VARCHAR(255),
   UNRESTAGREEMENTID           INTEGER,
   MATCHONATTRIBUTEID          INTEGER,
   ROOTCATEGORYID              INTEGER
);

ALTER TABLE APP.ASSETENTITY
   ADD CONSTRAINT SQL151101194326560
   PRIMARY KEY (ID);

CREATE INDEX APP.SQL151101194350360
   ON APP.ASSETENTITY (ROOTCATEGORYID ASC);

CREATE INDEX APP.SQL151101194349810
   ON APP.ASSETENTITY (MATCHONATTRIBUTEID ASC);


CREATE TABLE APP.ASSETENTITYUPLOADABLEBYGROUP
(
   ASSETENTITYID  INTEGER   NOT NULL,
   USERGROUPID    INTEGER   NOT NULL
);

ALTER TABLE APP.ASSETENTITYUPLOADABLEBYGROUP
   ADD CONSTRAINT SQL151101194335320
   PRIMARY KEY (ASSETENTITYID, USERGROUPID);

CREATE INDEX APP.SQL151101194401400
   ON APP.ASSETENTITYUPLOADABLEBYGROUP (USERGROUPID ASC);

CREATE INDEX APP.SQL151101194401050
   ON APP.ASSETENTITYUPLOADABLEBYGROUP (ASSETENTITYID ASC);


CREATE TABLE APP.ASSETTYPE
(
   ID    INTEGER        NOT NULL,
   NAME  VARCHAR(255)
);

ALTER TABLE APP.ASSETTYPE
   ADD CONSTRAINT SQL151101194325010
   PRIMARY KEY (ID);

CREATE TABLE APP.ATTRIBUTE
(
   ID                         INTEGER        NOT NULL,
   ALTTEXT                    VARCHAR(255),
   AUTOCOMPLETEPLUGIN         VARCHAR(255),
   BASEURL                    VARCHAR(255),
   DATEFORMATTYPE             SMALLINT,
   DEFAULTKEYWORDFILTER       VARCHAR(255),
   DEFAULTVALUE               VARCHAR(255),
   DISPLAYNAME                VARCHAR(255),
   ENFORCEUNIQUENESS          SMALLINT,
   FULLDATEPRECISIONREQUIRED  SMALLINT,
   GETDATAFROMCHILDREN        SMALLINT,
   HASSEARCHTOKENS            SMALLINT,
   HEIGHT                     INTEGER,
   HELPTEXT                   VARCHAR(255),
   HIDEFORSORT                SMALLINT,
   HIGHLIGHT                  SMALLINT,
   INCLUDEINSEARCHFORCHILD    SMALLINT,
   INCREMENTAMOUNT            INTEGER,
   INPUTMASK                  VARCHAR(255),
   ISAUTOCOMPLETE             SMALLINT,
   ISDESCRIPTIONATTRIBUTE     SMALLINT,
   ISEXTENDABLELIST           SMALLINT,
   ISFILTERED                 SMALLINT,
   ISHTML                     SMALLINT,
   ISKEYWORDSEARCHABLE        SMALLINT,
   ISMANDATORY                SMALLINT,
   ISMANDATORYBULKUPLOAD      SMALLINT,
   ISREADONLY                 SMALLINT,
   ISREQUIREDFORCOMPLETENESS  SMALLINT,
   ISSTATIC                   SMALLINT,
   KEYWORDIMPORTURL           VARCHAR(255),
   LABEL                      VARCHAR(255),
   MAXDECIMALPLACES           INTEGER,
   MAXDISPLAYLENGTH           INTEGER,
   MAXSIZE                    INTEGER,
   MINDECIMALPLACES           INTEGER,
   NAMEATTRIBUTE              SMALLINT,
   ONCHANGESCRIPT             VARCHAR(255),
   PLUGINCLASS                VARCHAR(255),
   PLUGINPARAMSATTRIBUTEIDS   VARCHAR(255),
   PREFIX                     VARCHAR(255),
   REQUIRESTRANSLATION        SMALLINT,
   SANITIZEHTML               SMALLINT,
   SEARCHHELPTEXT             VARCHAR(255),
   SEED                       INTEGER,
   SHOWONCHILD                SMALLINT,
   SHOWONDOWNLOAD             SMALLINT,
   SINGLEPOINTONLY            SMALLINT,
   STATICFIELDNAME            VARCHAR(255),
   TOKENDELIMITERREGEX        VARCHAR(255),
   TREEID                     INTEGER,
   VALUECOLUMNNAME            VARCHAR(255),
   VALUEIFNOTVISIBLE          VARCHAR(255),
   WIDTH                      INTEGER,
   ATTRIBUTETYPEID            INTEGER,
   PARENTID                   INTEGER
);

ALTER TABLE APP.ATTRIBUTE
   ADD CONSTRAINT SQL151101194330710
   PRIMARY KEY (ID);

CREATE INDEX APP.SQL151101194354350
   ON APP.ATTRIBUTE (PARENTID ASC);

CREATE INDEX APP.SQL151101194354090
   ON APP.ATTRIBUTE (ATTRIBUTETYPEID ASC);


CREATE TABLE APP.ATTRIBUTESTORAGETYPE
(
   ID    INTEGER        NOT NULL,
   NAME  VARCHAR(255)
);

ALTER TABLE APP.ATTRIBUTESTORAGETYPE
   ADD CONSTRAINT SQL151101194316260
   PRIMARY KEY (ID);

CREATE TABLE APP.ATTRIBUTETYPE
(
   ID                      INTEGER        NOT NULL,
   NAME                    VARCHAR(255),
   SEQUENCENUMBER          INTEGER,
   ATTRIBUTESTORAGETYPEID  INTEGER
);

ALTER TABLE APP.ATTRIBUTETYPE
   ADD CONSTRAINT SQL151101194317800
   PRIMARY KEY (ID);

CREATE INDEX APP.SQL151101194341660
   ON APP.ATTRIBUTETYPE (ATTRIBUTESTORAGETYPEID ASC);


CREATE TABLE APP.BRAND
(
   ID                     INTEGER        NOT NULL,
   CODE                   VARCHAR(255),
   CONTENTLISTIDENTIFIER  VARCHAR(255),
   CSSFILE                VARCHAR(255),
   EMAILDOMAINS           VARCHAR(255),
   LOGOALT                VARCHAR(255),
   LOGOFILE               VARCHAR(255),
   LOGOHEIGHT             INTEGER,
   LOGOWIDTH              INTEGER,
   NAME                   VARCHAR(255)
);

ALTER TABLE APP.BRAND
   ADD CONSTRAINT SQL151101194315770
   PRIMARY KEY (ID);

CREATE TABLE APP.CM_CATEGORY
(
   ID                    INTEGER        NOT NULL,
   ALLOWADVANCEDOPTIONS  SMALLINT,
   BITPOSITION           INTEGER,
   BROWSEASPANELS        SMALLINT,
   CANASSIGNIFNOTLEAF    SMALLINT,
   CANNOTBEDELETED       SMALLINT,
   DESCRIPTION           VARCHAR(255),
   ISBROWSABLE           SMALLINT,
   ISEXPIRED             SMALLINT,
   ISLISTBOXCATEGORY     SMALLINT,
   ISRESTRICTIVE         SMALLINT,
   NAME                  VARCHAR(255),
   SELECTEDONLOAD        SMALLINT,
   SEQUENCENUMBER        INTEGER,
   SHOWPROMOTEDONBROWSE  SMALLINT,
   SHOWRECENTONBROWSE    SMALLINT,
   SUMMARY               VARCHAR(255),
   VIEWTYPE              VARCHAR(255),
   WORKFLOWNAME          VARCHAR(255),
   CATEGORYTYPEID        INTEGER,
   EXTENSIONASSETID      INTEGER,
   PARENTID              INTEGER
);

ALTER TABLE APP.CM_CATEGORY
   ADD CONSTRAINT SQL151101194322400
   PRIMARY KEY (ID);

CREATE INDEX APP.SQL151101194345430
   ON APP.CM_CATEGORY (CATEGORYTYPEID ASC);

CREATE INDEX APP.SQL151101194345130
   ON APP.CM_CATEGORY (PARENTID ASC);

CREATE INDEX APP.SQL151101194344860
   ON APP.CM_CATEGORY (EXTENSIONASSETID ASC);


CREATE TABLE APP.CM_CATEGORYTYPE
(
   ID                    INTEGER        NOT NULL,
   DESCRIPTION           VARCHAR(255),
   ISALPHABETICORDER     SMALLINT,
   ISNAMEGLOBALLYUNIQUE  SMALLINT
);

ALTER TABLE APP.CM_CATEGORYTYPE
   ADD CONSTRAINT SQL151101194323010
   PRIMARY KEY (ID);

CREATE TABLE APP.COUNTRY
(
   ID                    INTEGER        NOT NULL,
   CODE                  VARCHAR(255),
   NAME                  VARCHAR(255),
   NATIVENAME            VARCHAR(255),
   SEQUENCENUMBER        INTEGER,
   TAXNUMBERFORMATREGEX  VARCHAR(255)
);

ALTER TABLE APP.COUNTRY
   ADD CONSTRAINT SQL151101194316860
   PRIMARY KEY (ID);

CREATE TABLE APP.CUSTOMER
(
   CUSTOMER_ID     VARCHAR(8)    NOT NULL,
   CITY            VARCHAR(40),
   EMAIL           VARCHAR(30),
   FIRST_NAME      VARCHAR(30),
   LAST_NAME       VARCHAR(30),
   MIDDLE_INITIAL  VARCHAR(1),
   PHONE           VARCHAR(16),
   STATE           VARCHAR(2),
   STREET          VARCHAR(40),
   ZIP             VARCHAR(5)
);

ALTER TABLE APP.CUSTOMER
   ADD CONSTRAINT SQL151101194332020
   PRIMARY KEY (CUSTOMER_ID);

CREATE TABLE APP.CUSTOMER_ACCOUNT_XREF
(
   ACCOUNT_ID   VARCHAR(8)   NOT NULL,
   CUSTOMER_ID  VARCHAR(8)   NOT NULL
);

ALTER TABLE APP.CUSTOMER_ACCOUNT_XREF
   ADD CONSTRAINT SQL151101194333260
   PRIMARY KEY (ACCOUNT_ID, CUSTOMER_ID);

CREATE INDEX APP.SQL151101194357460
   ON APP.CUSTOMER_ACCOUNT_XREF (CUSTOMER_ID ASC);

CREATE INDEX APP.SQL151101194357080
   ON APP.CUSTOMER_ACCOUNT_XREF (ACCOUNT_ID ASC);


CREATE TABLE APP.DIMACCOUNT
(
   ACCOUNTKEY                     INTEGER        NOT NULL,
   ACCOUNTCODEALTERNATEKEY        INTEGER,
   ACCOUNTDESCRIPTION             VARCHAR(50),
   ACCOUNTTYPE                    VARCHAR(50),
   CUSTOMMEMBEROPTIONS            VARCHAR(200),
   CUSTOMMEMBERS                  VARCHAR(300),
   OPERATOR                       VARCHAR(50),
   PARENTACCOUNTCODEALTERNATEKEY  INTEGER,
   VALUETYPE                      VARCHAR(50),
   PARENTACCOUNTKEY               INTEGER
);

ALTER TABLE APP.DIMACCOUNT
   ADD CONSTRAINT SQL151101194320500
   PRIMARY KEY (ACCOUNTKEY);

CREATE INDEX APP.SQL151101194344570
   ON APP.DIMACCOUNT (PARENTACCOUNTKEY ASC);

CREATE INDEX APP.SQL151101194337150
   ON APP.DIMACCOUNT (ACCOUNTCODEALTERNATEKEY ASC);


CREATE TABLE APP.DIMCURRENCY
(
   CURRENCYKEY           INTEGER       NOT NULL,
   CURRENCYALTERNATEKEY  VARCHAR(3)    NOT NULL,
   CURRENCYNAME          VARCHAR(50)   NOT NULL
);

ALTER TABLE APP.DIMCURRENCY
   ADD CONSTRAINT SQL151101194311750
   PRIMARY KEY (CURRENCYKEY);

CREATE UNIQUE INDEX APP.SQL151101194336130
   ON APP.DIMCURRENCY (CURRENCYALTERNATEKEY ASC);


CREATE TABLE APP.DIMCUSTOMER
(
   CUSTOMERKEY           INTEGER         NOT NULL,
   ADDRESSLINE1          VARCHAR(120),
   ADDRESSLINE2          VARCHAR(120),
   BIRTHDATE             DATE,
   COMMUTEDISTANCE       VARCHAR(15),
   CUSTOMERALTERNATEKEY  VARCHAR(15)     NOT NULL,
   DATEFIRSTPURCHASE     DATE,
   EMAILADDRESS          VARCHAR(50),
   ENGLISHEDUCATION      VARCHAR(40),
   ENGLISHOCCUPATION     VARCHAR(100),
   FIRSTNAME             VARCHAR(50),
   FRENCHEDUCATION       VARCHAR(40),
   FRENCHOCCUPATION      VARCHAR(100),
   GENDER                VARCHAR(1),
   HOUSEOWNERFLAG        VARCHAR(1),
   LASTNAME              VARCHAR(50),
   MARITALSTATUS         VARCHAR(1),
   MIDDLENAME            VARCHAR(50),
   NAMESTYLE             SMALLINT        DEFAULT 0,
   NUMBERCARSOWNED       SMALLINT,
   NUMBERCHILDRENATHOME  SMALLINT,
   PHONE                 VARCHAR(20),
   SPANISHEDUCATION      VARCHAR(40),
   SPANISHOCCUPATION     VARCHAR(100),
   SUFFIX                VARCHAR(10),
   TITLE                 VARCHAR(8),
   TOTALCHILDREN         SMALLINT,
   YEARLYINCOME          DECIMAL(19,4),
   GEOGRAPHYKEY          INTEGER
);

ALTER TABLE APP.DIMCUSTOMER
   ADD CONSTRAINT SQL151101194314370
   PRIMARY KEY (CUSTOMERKEY);

CREATE INDEX APP.SQL151101194340580
   ON APP.DIMCUSTOMER (GEOGRAPHYKEY ASC);

CREATE UNIQUE INDEX APP.SQL151101194336880
   ON APP.DIMCUSTOMER (CUSTOMERALTERNATEKEY ASC);


CREATE TABLE APP.DIMDATE
(
   DATEKEY               INTEGER       NOT NULL,
   CALENDARQUARTER       SMALLINT      NOT NULL,
   CALENDARSEMESTER      SMALLINT      NOT NULL,
   CALENDARYEAR          SMALLINT      NOT NULL,
   DAYNUMBEROFMONTH      SMALLINT      NOT NULL,
   DAYNUMBEROFWEEK       SMALLINT      NOT NULL,
   DAYNUMBEROFYEAR       SMALLINT      NOT NULL,
   ENGLISHDAYNAMEOFWEEK  VARCHAR(10)   NOT NULL,
   ENGLISHMONTHNAME      VARCHAR(10)   NOT NULL,
   FISCALQUARTER         SMALLINT      NOT NULL,
   FISCALSEMESTER        SMALLINT      NOT NULL,
   FISCALYEAR            SMALLINT      NOT NULL,
   FRENCHDAYNAMEOFWEEK   VARCHAR(10)   NOT NULL,
   FRENCHMONTHNAME       VARCHAR(10)   NOT NULL,
   FULLDATEALTERNATEKEY  DATE          NOT NULL,
   MONTHNUMBEROFYEAR     SMALLINT      NOT NULL,
   SPANISHDAYNAMEOFWEEK  VARCHAR(10)   NOT NULL,
   SPANISHMONTHNAME      VARCHAR(10)   NOT NULL,
   WEEKNUMBEROFYEAR      SMALLINT      NOT NULL
);

ALTER TABLE APP.DIMDATE
   ADD CONSTRAINT SQL151101194329680
   PRIMARY KEY (DATEKEY);

CREATE UNIQUE INDEX APP.SQL151101194338460
   ON APP.DIMDATE (FULLDATEALTERNATEKEY ASC);


CREATE TABLE APP.DIMDEPARTMENTGROUP
(
   DEPARTMENTGROUPKEY        INTEGER       NOT NULL,
   DEPARTMENTGROUPNAME       VARCHAR(50),
   PARENTDEPARTMENTGROUPKEY  INTEGER
);

ALTER TABLE APP.DIMDEPARTMENTGROUP
   ADD CONSTRAINT SQL151101194329220
   PRIMARY KEY (DEPARTMENTGROUPKEY);

CREATE INDEX APP.SQL151101194353250
   ON APP.DIMDEPARTMENTGROUP (PARENTDEPARTMENTGROUPKEY ASC);


CREATE TABLE APP.DIMEMPLOYEE
(
   EMPLOYEEKEY                           INTEGER         NOT NULL,
   BASERATE                              DECIMAL(19,4),
   BIRTHDATE                             DATE,
   CURRENTFLAG                           SMALLINT        DEFAULT 0 NOT NULL,
   DEPARTMENTNAME                        VARCHAR(50),
   EMAILADDRESS                          VARCHAR(50),
   EMERGENCYCONTACTNAME                  VARCHAR(50),
   EMERGENCYCONTACTPHONE                 VARCHAR(25),
   EMPLOYEENATIONALIDALTERNATEKEY        VARCHAR(15),
   EMPLOYEEPHOTO                         BLOB,
   ENDDATE                               DATE,
   FIRSTNAME                             VARCHAR(50)     NOT NULL,
   GENDER                                VARCHAR(1),
   HIREDATE                              DATE,
   LASTNAME                              VARCHAR(50)     NOT NULL,
   LOGINID                               VARCHAR(256),
   MARITALSTATUS                         VARCHAR(1),
   MIDDLENAME                            VARCHAR(50),
   NAMESTYLE                             SMALLINT        DEFAULT 0 NOT NULL,
   PARENTEMPLOYEENATIONALIDALTERNATEKEY  VARCHAR(15),
   PAYFREQUENCY                          SMALLINT,
   PHONE                                 VARCHAR(25),
   SALARIEDFLAG                          SMALLINT        DEFAULT 0,
   SALESPERSONFLAG                       SMALLINT        DEFAULT 0 NOT NULL,
   SICKLEAVEHOURS                        SMALLINT,
   STARTDATE                             DATE,
   STATUS                                VARCHAR(50),
   TITLE                                 VARCHAR(50),
   VACATIONHOURS                         SMALLINT,
   PARENTEMPLOYEEKEY                     INTEGER,
   SALESTERRITORYKEY                     INTEGER
);

ALTER TABLE APP.DIMEMPLOYEE
   ADD CONSTRAINT SQL151101194329990
   PRIMARY KEY (EMPLOYEEKEY);

CREATE INDEX APP.SQL151101194353870
   ON APP.DIMEMPLOYEE (PARENTEMPLOYEEKEY ASC);

CREATE INDEX APP.SQL151101194353600
   ON APP.DIMEMPLOYEE (SALESTERRITORYKEY ASC);


CREATE TABLE APP.DIMGEOGRAPHY
(
   GEOGRAPHYKEY              INTEGER       NOT NULL,
   CITY                      VARCHAR(30),
   COUNTRYREGIONCODE         VARCHAR(3),
   ENGLISHCOUNTRYREGIONNAME  VARCHAR(50),
   FRENCHCOUNTRYREGIONNAME   VARCHAR(50),
   IPADDRESSLOCATOR          VARCHAR(15),
   POSTALCODE                VARCHAR(15),
   SPANISHCOUNTRYREGIONNAME  VARCHAR(50),
   STATEPROVINCECODE         VARCHAR(3),
   STATEPROVINCENAME         VARCHAR(50),
   SALESTERRITORYKEY         INTEGER
);

ALTER TABLE APP.DIMGEOGRAPHY
   ADD CONSTRAINT SQL151101194312910
   PRIMARY KEY (GEOGRAPHYKEY);

CREATE INDEX APP.SQL151101194340380
   ON APP.DIMGEOGRAPHY (SALESTERRITORYKEY ASC);


CREATE TABLE APP.DIMORGANIZATION
(
   ORGANIZATIONKEY        INTEGER       NOT NULL,
   ORGANIZATIONNAME       VARCHAR(50),
   PERCENTAGEOFOWNERSHIP  VARCHAR(16),
   CURRENCYKEY            INTEGER,
   PARENTORGANIZATIONKEY  INTEGER
);

ALTER TABLE APP.DIMORGANIZATION
   ADD CONSTRAINT SQL151101194332380
   PRIMARY KEY (ORGANIZATIONKEY);

CREATE INDEX APP.SQL151101194356030
   ON APP.DIMORGANIZATION (PARENTORGANIZATIONKEY ASC);

CREATE INDEX APP.SQL151101194355830
   ON APP.DIMORGANIZATION (CURRENCYKEY ASC);


CREATE TABLE APP.DIMPRODUCT
(
   PRODUCTKEY             INTEGER         NOT NULL,
   ARABICDESCRIPTION      VARCHAR(400),
   CHINESEDESCRIPTION     VARCHAR(400),
   CLASS                  VARCHAR(2),
   COLOR                  VARCHAR(15)     NOT NULL,
   DAYSTOMANUFACTURE      INTEGER,
   DEALERPRICE            DECIMAL(19,4),
   ENDDATE                TIMESTAMP,
   ENGLISHDESCRIPTION     VARCHAR(400),
   ENGLISHPRODUCTNAME     VARCHAR(50)     NOT NULL,
   FINISHEDGOODSFLAG      SMALLINT        DEFAULT 0 NOT NULL,
   FRENCHDESCRIPTION      VARCHAR(400),
   FRENCHPRODUCTNAME      VARCHAR(50)     NOT NULL,
   GERMANDESCRIPTION      VARCHAR(400),
   HEBREWDESCRIPTION      VARCHAR(400),
   JAPANESEDESCRIPTION    VARCHAR(400),
   LARGEPHOTO             BLOB,
   LISTPRICE              DECIMAL(19,4),
   MODELNAME              VARCHAR(50),
   PRODUCTALTERNATEKEY    VARCHAR(25),
   PRODUCTLINE            VARCHAR(2),
   REORDERPOINT           SMALLINT,
   SAFETYSTOCKLEVEL       SMALLINT,
   SIZE                   VARCHAR(50),
   SIZERANGE              VARCHAR(50),
   SIZEUNITMEASURECODE    VARCHAR(3),
   SPANISHPRODUCTNAME     VARCHAR(50)     NOT NULL,
   STANDARDCOST           DECIMAL(19,4),
   STARTDATE              TIMESTAMP,
   STATUS                 VARCHAR(7),
   STYLE                  VARCHAR(2),
   THAIDESCRIPTION        VARCHAR(400),
   TURKISHDESCRIPTION     VARCHAR(400),
   WEIGHT                 DOUBLE,
   WEIGHTUNITMEASURECODE  VARCHAR(3),
   PRODUCTSUBCATEGORYKEY  INTEGER
);

ALTER TABLE APP.DIMPRODUCT
   ADD CONSTRAINT SQL151101194323880
   PRIMARY KEY (PRODUCTKEY);

CREATE INDEX APP.SQL151101194338070
   ON APP.DIMPRODUCT (PRODUCTALTERNATEKEY ASC, STARTDATE ASC);

CREATE INDEX APP.SQL151101194345970
   ON APP.DIMPRODUCT (PRODUCTSUBCATEGORYKEY ASC);


CREATE TABLE APP.DIMPRODUCTCATEGORY
(
   PRODUCTCATEGORYKEY           INTEGER       NOT NULL,
   ENGLISHPRODUCTCATEGORYNAME   VARCHAR(50)   NOT NULL,
   FRENCHPRODUCTCATEGORYNAME    VARCHAR(50)   NOT NULL,
   PRODUCTCATEGORYALTERNATEKEY  INTEGER,
   SPANISHPRODUCTCATEGORYNAME   VARCHAR(50)   NOT NULL
);

ALTER TABLE APP.DIMPRODUCTCATEGORY
   ADD CONSTRAINT SQL151101194321840
   PRIMARY KEY (PRODUCTCATEGORYKEY);

CREATE INDEX APP.SQL151101194337620
   ON APP.DIMPRODUCTCATEGORY (PRODUCTCATEGORYALTERNATEKEY ASC);


CREATE TABLE APP.DIMPRODUCTSUBCATEGORY
(
   PRODUCTSUBCATEGORYKEY           INTEGER       NOT NULL,
   ENGLISHPRODUCTSUBCATEGORYNAME   VARCHAR(50)   NOT NULL,
   FRENCHPRODUCTSUBCATEGORYNAME    VARCHAR(50)   NOT NULL,
   PRODUCTSUBCATEGORYALTERNATEKEY  INTEGER,
   SPANISHPRODUCTSUBCATEGORYNAME   VARCHAR(50)   NOT NULL,
   PRODUCTCATEGORYKEY              INTEGER
);

ALTER TABLE APP.DIMPRODUCTSUBCATEGORY
   ADD CONSTRAINT SQL151101194332650
   PRIMARY KEY (PRODUCTSUBCATEGORYKEY);

CREATE INDEX APP.SQL151101194338740
   ON APP.DIMPRODUCTSUBCATEGORY (PRODUCTSUBCATEGORYALTERNATEKEY ASC);

CREATE INDEX APP.SQL151101194356300
   ON APP.DIMPRODUCTSUBCATEGORY (PRODUCTCATEGORYKEY ASC);


CREATE TABLE APP.DIMPROMOTION
(
   PROMOTIONKEY              INTEGER        NOT NULL,
   DISCOUNTPCT               DOUBLE,
   ENDDATE                   TIMESTAMP,
   ENGLISHPROMOTIONCATEGORY  VARCHAR(50),
   ENGLISHPROMOTIONNAME      VARCHAR(255),
   ENGLISHPROMOTIONTYPE      VARCHAR(50),
   FRENCHPROMOTIONCATEGORY   VARCHAR(50),
   FRENCHPROMOTIONNAME       VARCHAR(255),
   FRENCHPROMOTIONTYPE       VARCHAR(50),
   MAXQTY                    INTEGER,
   MINQTY                    INTEGER,
   PROMOTIONALTERNATEKEY     INTEGER,
   SPANISHPROMOTIONCATEGORY  VARCHAR(50),
   SPANISHPROMOTIONNAME      VARCHAR(255),
   SPANISHPROMOTIONTYPE      VARCHAR(50),
   STARTDATE                 TIMESTAMP      NOT NULL
);

ALTER TABLE APP.DIMPROMOTION
   ADD CONSTRAINT SQL151101194321080
   PRIMARY KEY (PROMOTIONKEY);

CREATE INDEX APP.SQL151101194337400
   ON APP.DIMPROMOTION (PROMOTIONALTERNATEKEY ASC);


CREATE TABLE APP.DIMRESELLER
(
   RESELLERKEY           INTEGER         NOT NULL,
   ADDRESSLINE1          VARCHAR(60),
   ADDRESSLINE2          VARCHAR(60),
   ANNUALREVENUE         DECIMAL(19,4),
   ANNUALSALES           DECIMAL(19,4),
   BANKNAME              VARCHAR(50),
   BUSINESSTYPE          VARCHAR(20)     NOT NULL,
   FIRSTORDERYEAR        INTEGER,
   LASTORDERYEAR         INTEGER,
   MINPAYMENTAMOUNT      DECIMAL(19,4),
   MINPAYMENTTYPE        SMALLINT,
   NUMBEREMPLOYEES       INTEGER,
   ORDERFREQUENCY        CHAR(1),
   ORDERMONTH            SMALLINT,
   PHONE                 VARCHAR(25),
   PRODUCTLINE           VARCHAR(50),
   RESELLERALTERNATEKEY  VARCHAR(15),
   RESELLERNAME          VARCHAR(50)     NOT NULL,
   YEAROPENED            INTEGER,
   GEOGRAPHYKEY          INTEGER
);

ALTER TABLE APP.DIMRESELLER
   ADD CONSTRAINT SQL151101194323430
   PRIMARY KEY (RESELLERKEY);

CREATE INDEX APP.SQL151101194337810
   ON APP.DIMRESELLER (RESELLERALTERNATEKEY ASC);

CREATE INDEX APP.SQL151101194345680
   ON APP.DIMRESELLER (GEOGRAPHYKEY ASC);


CREATE TABLE APP.DIMSALESREASON
(
   SALESREASONKEY           INTEGER       NOT NULL,
   SALESREASONALTERNATEKEY  INTEGER       NOT NULL,
   SALESREASONNAME          VARCHAR(50)   NOT NULL,
   SALESREASONREASONTYPE    VARCHAR(50)   NOT NULL
);

ALTER TABLE APP.DIMSALESREASON
   ADD CONSTRAINT SQL151101194317340
   PRIMARY KEY (SALESREASONKEY);

CREATE TABLE APP.DIMSALESTERRITORY
(
   SALESTERRITORYKEY           INTEGER       NOT NULL,
   SALESTERRITORYALTERNATEKEY  INTEGER,
   SALESTERRITORYCOUNTRY       VARCHAR(50)   NOT NULL,
   SALESTERRITORYGROUP         VARCHAR(50),
   SALESTERRITORYIMAGE         BLOB,
   SALESTERRITORYREGION        VARCHAR(50)   NOT NULL
);

ALTER TABLE APP.DIMSALESTERRITORY
   ADD CONSTRAINT SQL151101194313410
   PRIMARY KEY (SALESTERRITORYKEY);

CREATE INDEX APP.SQL151101194336460
   ON APP.DIMSALESTERRITORY (SALESTERRITORYALTERNATEKEY ASC);


CREATE TABLE APP.DIMSCENARIO
(
   SCENARIOKEY   INTEGER       NOT NULL,
   SCENARIONAME  VARCHAR(50)
);

ALTER TABLE APP.DIMSCENARIO
   ADD CONSTRAINT SQL151101194312130
   PRIMARY KEY (SCENARIOKEY);

CREATE TABLE APP.DIVISION
(
   ID    INTEGER        NOT NULL,
   NAME  VARCHAR(255)
);

ALTER TABLE APP.DIVISION
   ADD CONSTRAINT SQL151101194318550
   PRIMARY KEY (ID);

CREATE TABLE APP.FACTCALLCENTER
(
   FACTCALLCENTERID     INTEGER       NOT NULL,
   AUTOMATICRESPONSES   INTEGER       NOT NULL,
   AVERAGETIMEPERISSUE  SMALLINT      NOT NULL,
   CALLS                INTEGER       NOT NULL,
   DATE                 TIMESTAMP,
   ISSUESRAISED         SMALLINT      NOT NULL,
   LEVELONEOPERATORS    SMALLINT      NOT NULL,
   LEVELTWOOPERATORS    SMALLINT      NOT NULL,
   ORDERS               INTEGER       NOT NULL,
   SERVICEGRADE         DOUBLE        NOT NULL,
   SHIFT                VARCHAR(20)   NOT NULL,
   TOTALOPERATORS       SMALLINT      NOT NULL,
   WAGETYPE             VARCHAR(15)   NOT NULL,
   DATEKEY              INTEGER       NOT NULL
);

ALTER TABLE APP.FACTCALLCENTER
   ADD CONSTRAINT SQL151101194327810
   PRIMARY KEY (FACTCALLCENTERID);

CREATE UNIQUE INDEX APP.SQL151101194338290
   ON APP.FACTCALLCENTER (DATEKEY ASC, SHIFT ASC);

CREATE INDEX APP.SQL151101194352220
   ON APP.FACTCALLCENTER (DATEKEY ASC);


CREATE TABLE APP.FACTCURRENCYRATE
(
   AVERAGERATE   DOUBLE      NOT NULL,
   DATE          TIMESTAMP,
   ENDOFDAYRATE  DOUBLE      NOT NULL,
   DATEKEY       INTEGER     NOT NULL,
   CURRENCYKEY   INTEGER     NOT NULL
);

ALTER TABLE APP.FACTCURRENCYRATE
   ADD CONSTRAINT SQL151101194331690
   PRIMARY KEY (DATEKEY, CURRENCYKEY);

CREATE INDEX APP.SQL151101194355480
   ON APP.FACTCURRENCYRATE (DATEKEY ASC);

CREATE INDEX APP.SQL151101194355310
   ON APP.FACTCURRENCYRATE (CURRENCYKEY ASC);


CREATE TABLE APP.FACTINTERNETSALES
(
   CARRIERTRACKINGNUMBER  VARCHAR(25),
   CUSTOMERPONUMBER       VARCHAR(25),
   DISCOUNTAMOUNT         DOUBLE          NOT NULL,
   DUEDATE                TIMESTAMP,
   EXTENDEDAMOUNT         DECIMAL(19,4)   NOT NULL,
   FREIGHT                DECIMAL(19,4)   NOT NULL,
   ORDERDATE              TIMESTAMP,
   ORDERQUANTITY          SMALLINT        NOT NULL,
   PRODUCTSTANDARDCOST    DECIMAL(19,4)   NOT NULL,
   REVISIONNUMBER         SMALLINT        NOT NULL,
   SALESAMOUNT            DECIMAL(19,4)   NOT NULL,
   SHIPDATE               TIMESTAMP,
   TAXAMT                 DECIMAL(19,4)   NOT NULL,
   TOTALPRODUCTCOST       DECIMAL(19,4)   NOT NULL,
   UNITPRICE              DECIMAL(19,4)   NOT NULL,
   UNITPRICEDISCOUNTPCT   DOUBLE          NOT NULL,
   SALESORDERNUMBER       VARCHAR(20)     NOT NULL,
   SALESORDERLINENUMBER   SMALLINT        NOT NULL,
   CURRENCYKEY            INTEGER         NOT NULL,
   CUSTOMERKEY            INTEGER         NOT NULL,
   DUEDATEKEY             INTEGER         NOT NULL,
   ORDERDATEKEY           INTEGER         NOT NULL,
   PRODUCTKEY             INTEGER         NOT NULL,
   PROMOTIONKEY           INTEGER         NOT NULL,
   SALESTERRITORYKEY      INTEGER         NOT NULL,
   SHIPDATEKEY            INTEGER         NOT NULL
);

ALTER TABLE APP.FACTINTERNETSALES
   ADD CONSTRAINT SQL151101194327040
   PRIMARY KEY (SALESORDERNUMBER, SALESORDERLINENUMBER);

CREATE INDEX APP.SQL151101194351160
   ON APP.FACTINTERNETSALES (CURRENCYKEY ASC);

CREATE INDEX APP.SQL151101194352050
   ON APP.FACTINTERNETSALES (SALESTERRITORYKEY ASC);

CREATE INDEX APP.SQL151101194351670
   ON APP.FACTINTERNETSALES (PROMOTIONKEY ASC);

CREATE INDEX APP.SQL151101194350780
   ON APP.FACTINTERNETSALES (ORDERDATEKEY ASC);

CREATE INDEX APP.SQL151101194350970
   ON APP.FACTINTERNETSALES (PRODUCTKEY ASC);

CREATE INDEX APP.SQL151101194351420
   ON APP.FACTINTERNETSALES (CUSTOMERKEY ASC);

CREATE INDEX APP.SQL151101194351860
   ON APP.FACTINTERNETSALES (SHIPDATEKEY ASC);

CREATE INDEX APP.SQL151101194350520
   ON APP.FACTINTERNETSALES (DUEDATEKEY ASC);


CREATE TABLE APP.FACTINTERNETSALESREASON
(
   SALESREASONKEY        INTEGER       NOT NULL,
   SALESORDERNUMBER      VARCHAR(20)   NOT NULL,
   SALESORDERLINENUMBER  SMALLINT      NOT NULL
);

ALTER TABLE APP.FACTINTERNETSALESREASON
   ADD CONSTRAINT SQL151101194333580
   PRIMARY KEY (SALESREASONKEY, SALESORDERNUMBER, SALESORDERLINENUMBER);

CREATE INDEX APP.SQL151101194357990
   ON APP.FACTINTERNETSALESREASON (SALESORDERNUMBER ASC, SALESORDERLINENUMBER ASC);

CREATE INDEX APP.SQL151101194357710
   ON APP.FACTINTERNETSALESREASON (SALESREASONKEY ASC);


CREATE TABLE APP.FACTPRODUCTINVENTORY
(
   MOVEMENTDATE  DATE            NOT NULL,
   UNITCOST      DECIMAL(19,4)   NOT NULL,
   UNITSBALANCE  INTEGER         NOT NULL,
   UNITSIN       INTEGER         NOT NULL,
   UNITSOUT      INTEGER         NOT NULL,
   DATEKEY       INTEGER         NOT NULL,
   PRODUCTKEY    INTEGER         NOT NULL
);

ALTER TABLE APP.FACTPRODUCTINVENTORY
   ADD CONSTRAINT SQL151101194319090
   PRIMARY KEY (DATEKEY, PRODUCTKEY);

CREATE INDEX APP.SQL151101194342070
   ON APP.FACTPRODUCTINVENTORY (DATEKEY ASC);

CREATE INDEX APP.SQL151101194341850
   ON APP.FACTPRODUCTINVENTORY (PRODUCTKEY ASC);


CREATE TABLE APP.FACTRESELLERSALES
(
   CARRIERTRACKINGNUMBER  VARCHAR(25),
   CUSTOMERPONUMBER       VARCHAR(25),
   DISCOUNTAMOUNT         DOUBLE,
   DUEDATE                TIMESTAMP,
   EXTENDEDAMOUNT         DECIMAL(19,4),
   FREIGHT                DECIMAL(19,4),
   ORDERDATE              TIMESTAMP,
   ORDERQUANTITY          SMALLINT,
   PRODUCTSTANDARDCOST    DECIMAL(19,4),
   REVISIONNUMBER         SMALLINT,
   SALESAMOUNT            DECIMAL(19,4),
   SHIPDATE               TIMESTAMP,
   TAXAMT                 DECIMAL(19,4),
   TOTALPRODUCTCOST       DECIMAL(19,4),
   UNITPRICE              DECIMAL(19,4),
   UNITPRICEDISCOUNTPCT   DOUBLE,
   SALESORDERNUMBER       VARCHAR(20)     NOT NULL,
   SALESORDERLINENUMBER   SMALLINT        NOT NULL,
   CURRENCYKEY            INTEGER         NOT NULL,
   DUEDATEKEY             INTEGER         NOT NULL,
   EMPLOYEEKEY            INTEGER         NOT NULL,
   ORDERDATEKEY           INTEGER         NOT NULL,
   PRODUCTKEY             INTEGER         NOT NULL,
   PROMOTIONKEY           INTEGER         NOT NULL,
   RESELLERKEY            INTEGER         NOT NULL,
   SALESTERRITORYKEY      INTEGER         NOT NULL,
   SHIPDATEKEY            INTEGER         NOT NULL
);

ALTER TABLE APP.FACTRESELLERSALES
   ADD CONSTRAINT SQL151101194319950
   PRIMARY KEY (SALESORDERNUMBER, SALESORDERLINENUMBER);

CREATE INDEX APP.SQL151101194343030
   ON APP.FACTRESELLERSALES (DUEDATEKEY ASC);

CREATE INDEX APP.SQL151101194343280
   ON APP.FACTRESELLERSALES (SALESTERRITORYKEY ASC);

CREATE INDEX APP.SQL151101194343160
   ON APP.FACTRESELLERSALES (RESELLERKEY ASC);

CREATE INDEX APP.SQL151101194344360
   ON APP.FACTRESELLERSALES (PROMOTIONKEY ASC);

CREATE INDEX APP.SQL151101194343600
   ON APP.FACTRESELLERSALES (PRODUCTKEY ASC);

CREATE INDEX APP.SQL151101194343820
   ON APP.FACTRESELLERSALES (CURRENCYKEY ASC);

CREATE INDEX APP.SQL151101194342770
   ON APP.FACTRESELLERSALES (EMPLOYEEKEY ASC);

CREATE INDEX APP.SQL151101194343970
   ON APP.FACTRESELLERSALES (SHIPDATEKEY ASC);

CREATE INDEX APP.SQL151101194342530
   ON APP.FACTRESELLERSALES (ORDERDATEKEY ASC);


CREATE TABLE APP.FACTSALESQUOTA
(
   SALESQUOTAKEY     INTEGER         NOT NULL,
   CALENDARQUARTER   SMALLINT        NOT NULL,
   CALENDARYEAR      SMALLINT        NOT NULL,
   DATE              TIMESTAMP,
   SALESAMOUNTQUOTA  DECIMAL(19,4)   NOT NULL,
   DATEKEY           INTEGER         NOT NULL,
   EMPLOYEEKEY       INTEGER         NOT NULL
);

ALTER TABLE APP.FACTSALESQUOTA
   ADD CONSTRAINT SQL151101194325640
   PRIMARY KEY (SALESQUOTAKEY);

CREATE INDEX APP.SQL151101194347330
   ON APP.FACTSALESQUOTA (EMPLOYEEKEY ASC);

CREATE INDEX APP.SQL151101194347500
   ON APP.FACTSALESQUOTA (DATEKEY ASC);


CREATE TABLE APP.FACTSURVEYRESPONSE
(
   SURVEYRESPONSEKEY              INTEGER       NOT NULL,
   DATE                           TIMESTAMP,
   ENGLISHPRODUCTCATEGORYNAME     VARCHAR(50)   NOT NULL,
   ENGLISHPRODUCTSUBCATEGORYNAME  VARCHAR(50)   NOT NULL,
   PRODUCTCATEGORYKEY             INTEGER       NOT NULL,
   PRODUCTSUBCATEGORYKEY          INTEGER       NOT NULL,
   CUSTOMERKEY                    INTEGER       NOT NULL,
   DATEKEY                        INTEGER       NOT NULL
);

ALTER TABLE APP.FACTSURVEYRESPONSE
   ADD CONSTRAINT SQL151101194328340
   PRIMARY KEY (SURVEYRESPONSEKEY);

CREATE INDEX APP.SQL151101194352590
   ON APP.FACTSURVEYRESPONSE (CUSTOMERKEY ASC);

CREATE INDEX APP.SQL151101194352950
   ON APP.FACTSURVEYRESPONSE (DATEKEY ASC);


CREATE TABLE APP.FILEFORMAT
(
   ID                       INTEGER        NOT NULL,
   CANUPLOADTHUMBNAIL       SMALLINT,
   CANVIEWORIGINAL          SMALLINT,
   COMPRESSEDINZIP          SMALLINT,
   CONTENTTYPE              VARCHAR(255),
   CONVERTINDIVIDUALLAYERS  SMALLINT,
   CONVERTERCLASS           VARCHAR(255),
   DESCRIPTION              VARCHAR(255),
   FILEEXTENSION            VARCHAR(255),
   ISCONVERSIONTARGET       SMALLINT,
   ISCONVERTABLE            SMALLINT,
   ISINDEXABLE              SMALLINT,
   ISROTATABLE              SMALLINT,
   NAME                     VARCHAR(255),
   PREVIEWHEIGHT            INTEGER,
   PREVIEWINCLUDE           VARCHAR(255),
   PREVIEWWIDTH             INTEGER,
   SUPPORTSTRANSPARENCY     SMALLINT,
   THUMBNAILFILELOCATION    VARCHAR(255),
   TOTEXTCONVERTERCLASS     VARCHAR(255),
   VIEWFILEINCLUDE          VARCHAR(255),
   ASSETTYPEID              INTEGER
);

ALTER TABLE APP.FILEFORMAT
   ADD CONSTRAINT SQL151101194316590
   PRIMARY KEY (ID);

CREATE INDEX APP.SQL151101194341290
   ON APP.FILEFORMAT (ASSETTYPEID ASC);


CREATE TABLE APP.INDESIGNLINKEDRESOURCE
(
   LINKEDASSETID  INTEGER   NOT NULL,
   ASSETID        INTEGER   NOT NULL
);

ALTER TABLE APP.INDESIGNLINKEDRESOURCE
   ADD CONSTRAINT SQL151101194334980
   PRIMARY KEY (LINKEDASSETID, ASSETID);

CREATE INDEX APP.SQL151101194400610
   ON APP.INDESIGNLINKEDRESOURCE (ASSETID ASC);

CREATE INDEX APP.SQL151101194400360
   ON APP.INDESIGNLINKEDRESOURCE (LINKEDASSETID ASC);


CREATE TABLE APP.LANGUAGE
(
   ID                 INTEGER        NOT NULL,
   CODE               VARCHAR(255),
   ICONFILENAME       VARCHAR(255),
   ISDEFAULT          SMALLINT,
   ISRIGHTTOLEFT      SMALLINT,
   ISSUSPENDED        SMALLINT,
   NAME               VARCHAR(255),
   NATIVENAME         VARCHAR(255),
   USESLATINALPHABET  SMALLINT
);

ALTER TABLE APP.LANGUAGE
   ADD CONSTRAINT SQL151101194328870
   PRIMARY KEY (ID);

CREATE TABLE APP.MENUITEM
(
   ITEMIDENTIFIER       VARCHAR(255)   NOT NULL,
   ISHIDDEN             SMALLINT,
   ISOPENEDINNEWWINDOW  SMALLINT,
   ITEMCOMMENT          VARCHAR(255),
   SEQUENCENUMBER       INTEGER
);

ALTER TABLE APP.MENUITEM
   ADD CONSTRAINT SQL151101194330430
   PRIMARY KEY (ITEMIDENTIFIER);

CREATE TABLE APP.MENUITEMHIDDENFROMGROUP
(
   MENUITEMIDENTIFIER  VARCHAR(255)   NOT NULL,
   USERGROUPID         INTEGER        NOT NULL
);

ALTER TABLE APP.MENUITEMHIDDENFROMGROUP
   ADD CONSTRAINT SQL151101194335760
   PRIMARY KEY (MENUITEMIDENTIFIER, USERGROUPID);

CREATE INDEX APP.SQL151101194401720
   ON APP.MENUITEMHIDDENFROMGROUP (MENUITEMIDENTIFIER ASC);

CREATE INDEX APP.SQL151101194402280
   ON APP.MENUITEMHIDDENFROMGROUP (USERGROUPID ASC);


CREATE TABLE APP.NEXT_ID
(
   BEANNAME  VARCHAR(30)   NOT NULL,
   ID        BIGINT
);

ALTER TABLE APP.NEXT_ID
   ADD CONSTRAINT SQL151101194331010
   PRIMARY KEY (BEANNAME);

CREATE TABLE APP.ORGUNIT
(
   ID                         INTEGER        NOT NULL,
   DISKQUOTAMB                INTEGER,
   NOTES                      VARCHAR(255),
   ADMINGROUPID               INTEGER,
   ROOTDESCRIPTIVECATEGORYID  INTEGER,
   STANDARDGROUPID            INTEGER,
   ROOTORGUNITCATEGORYID      INTEGER
);

ALTER TABLE APP.ORGUNIT
   ADD CONSTRAINT SQL151101194312590
   PRIMARY KEY (ID);

CREATE INDEX APP.SQL151101194340040
   ON APP.ORGUNIT (ADMINGROUPID ASC);

CREATE INDEX APP.SQL151101194339430
   ON APP.ORGUNIT (STANDARDGROUPID ASC);

CREATE INDEX APP.SQL151101194338960
   ON APP.ORGUNIT (ROOTDESCRIPTIVECATEGORYID ASC);

CREATE INDEX APP.SQL151101194339820
   ON APP.ORGUNIT (ROOTORGUNITCATEGORYID ASC);


CREATE TABLE APP.ORGUNITGROUP
(
   ORGUNITID    INTEGER   NOT NULL,
   USERGROUPID  INTEGER   NOT NULL
);

ALTER TABLE APP.ORGUNITGROUP
   ADD CONSTRAINT SQL151101194332940
   PRIMARY KEY (ORGUNITID, USERGROUPID);

CREATE INDEX APP.SQL151101194356770
   ON APP.ORGUNITGROUP (USERGROUPID ASC);

CREATE INDEX APP.SQL151101194356580
   ON APP.ORGUNITGROUP (ORGUNITID ASC);


CREATE TABLE APP.REGION
(
   ID         INTEGER        NOT NULL,
   CODE       VARCHAR(255),
   NAME       VARCHAR(255),
   COUNTRYID  INTEGER
);

ALTER TABLE APP.REGION
   ADD CONSTRAINT SQL151101194319560
   PRIMARY KEY (ID);

CREATE INDEX APP.SQL151101194342210
   ON APP.REGION (COUNTRYID ASC);


CREATE TABLE APP.USEREDITLANGUAGE
(
   USERID      INTEGER   NOT NULL,
   LANGUAGEID  INTEGER   NOT NULL
);

ALTER TABLE APP.USEREDITLANGUAGE
   ADD CONSTRAINT SQL151101194333940
   PRIMARY KEY (USERID, LANGUAGEID);

CREATE INDEX APP.SQL151101194358320
   ON APP.USEREDITLANGUAGE (LANGUAGEID ASC);

CREATE INDEX APP.SQL151101194358570
   ON APP.USEREDITLANGUAGE (USERID ASC);


CREATE TABLE APP.USERGROUP
(
   ID                          INTEGER        NOT NULL,
   ADVANCEDVIEWING             SMALLINT,
   AUTOMATICBRANDREGISTER      SMALLINT,
   CANADDEMPTYASSETS           SMALLINT,
   CANEMAILASSETS              SMALLINT,
   CANEXPORTASSETS             SMALLINT,
   CANINVITEUSERS              SMALLINT,
   CANONLYEDITOWN              SMALLINT,
   CANPUBLISHASSETBOX          SMALLINT,
   CANREPURPOSEASSETS          SMALLINT,
   CANSEESOURCEPATH            SMALLINT,
   CANSELECTONREGISTRATION     SMALLINT,
   CANVIEWLARGERSIZE           SMALLINT,
   DESCRIPTION                 VARCHAR(255),
   DISCOUNTPERCENTAGE          INTEGER,
   DOWNLOADLIMIT               INTEGER,
   DOWNLOADLIMITPERIOD         VARCHAR(255),
   IPMAPPING                   VARCHAR(255),
   ISDEFAULTGROUP              SMALLINT,
   MAPPING                     VARCHAR(255),
   MAXDOWNLOADHEIGHT           INTEGER,
   MAXDOWNLOADWIDTH            INTEGER,
   NAME                        VARCHAR(255),
   SEQUENCENUMBER              INTEGER,
   URLMAPPING                  VARCHAR(255),
   BRANDID                     INTEGER,
   HOMEPAGEMENUITEMIDENTIFIER  VARCHAR(255)
);

ALTER TABLE APP.USERGROUP
   ADD CONSTRAINT SQL151101194331320
   PRIMARY KEY (ID);

CREATE INDEX APP.SQL151101194354730
   ON APP.USERGROUP (BRANDID ASC);

CREATE INDEX APP.SQL151101194355090
   ON APP.USERGROUP (HOMEPAGEMENUITEMIDENTIFIER ASC);


CREATE TABLE APP.USERINGROUP
(
   USERID       INTEGER   NOT NULL,
   USERGROUPID  INTEGER   NOT NULL
);

ALTER TABLE APP.USERINGROUP
   ADD CONSTRAINT SQL151101194334240
   PRIMARY KEY (USERID, USERGROUPID);

CREATE INDEX APP.SQL151101194359440
   ON APP.USERINGROUP (USERID ASC);

CREATE INDEX APP.SQL151101194359050
   ON APP.USERINGROUP (USERGROUPID ASC);



ALTER TABLE APP.ADDRESS
  ADD CONSTRAINT ADDRESS_COUNTRYID FOREIGN KEY (COUNTRYID)
  REFERENCES APP.COUNTRY (ID)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.ADDRESS
  ADD CONSTRAINT ADDRESS_REGIONID FOREIGN KEY (REGIONID)
  REFERENCES APP.REGION (ID)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.ALLOWABLEENTITYASSETTYPE
  ADD CONSTRAINT LLWBLNTTYSSSTNTTYD FOREIGN KEY (ASSETENTITYID)
  REFERENCES APP.ASSETENTITY (ID)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.ALLOWABLEENTITYASSETTYPE
  ADD CONSTRAINT LLWBLNTTYSSSSTTYPD FOREIGN KEY (ASSETTYPEID)
  REFERENCES APP.ASSETTYPE (ID)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.ASSET
  ADD CONSTRAINT SSTCRRENTVERSIONID FOREIGN KEY (CURRENTVERSIONID)
  REFERENCES APP.ASSET (ID)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.ASSET
  ADD CONSTRAINT SSTSBMTTEDBYUSERID FOREIGN KEY (SUBMITTEDBYUSERID)
  REFERENCES APP.ASSETBANKUSER (ID)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.ASSET
  ADD CONSTRAINT ASSETADDEDBYUSERID FOREIGN KEY (ADDEDBYUSERID)
  REFERENCES APP.ASSETBANKUSER (ID)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.ASSET
  ADD CONSTRAINT SSTLSTMDFDBYUSERID FOREIGN KEY (LASTMODIFIEDBYUSERID)
  REFERENCES APP.ASSETBANKUSER (ID)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.ASSET
  ADD CONSTRAINT SSTFLCHCKDTBYSERID FOREIGN KEY (FILECHECKEDOUTBYUSERID)
  REFERENCES APP.ASSETBANKUSER (ID)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.ASSET
  ADD CONSTRAINT ASSETASSETENTITYID FOREIGN KEY (ASSETENTITYID)
  REFERENCES APP.ASSETENTITY (ID)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.ASSET
  ADD CONSTRAINT ASSET_ASSETTYPEID FOREIGN KEY (ASSETTYPEID)
  REFERENCES APP.ASSETTYPE (ID)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.ASSET
  ADD CONSTRAINT ASSET_FILEFORMATID FOREIGN KEY (FILEFORMATID)
  REFERENCES APP.FILEFORMAT (ID)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.ASSETBANKUSER
  ADD CONSTRAINT SSTBANKUSERDDRSSID FOREIGN KEY (ADDRESSID)
  REFERENCES APP.ADDRESS (ID)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.ASSETBANKUSER
  ADD CONSTRAINT SSTBNKSRLSTMDFDBYD FOREIGN KEY (LASTMODIFIEDBYID)
  REFERENCES APP.ASSETBANKUSER (ID)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.ASSETBANKUSER
  ADD CONSTRAINT SSTBNKSRNVTDBYSRID FOREIGN KEY (INVITEDBYUSERID)
  REFERENCES APP.ASSETBANKUSER (ID)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.ASSETBANKUSER
  ADD CONSTRAINT SSTBANKUSERDVSONID FOREIGN KEY (DIVISIONID)
  REFERENCES APP.DIVISION (ID)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.ASSETBANKUSER
  ADD CONSTRAINT SSTBANKUSERLNGGEID FOREIGN KEY (LANGUAGEID)
  REFERENCES APP.LANGUAGE (ID)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.ASSETBANKUSER
  ADD CONSTRAINT SSTBNKSRRQSTDRGNTD FOREIGN KEY (REQUESTEDORGUNITID)
  REFERENCES APP.ORGUNIT (ID)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.ASSETENTITY
  ADD CONSTRAINT SSTNTTYMTCHNTTRBTD FOREIGN KEY (MATCHONATTRIBUTEID)
  REFERENCES APP.ATTRIBUTE (ID)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.ASSETENTITY
  ADD CONSTRAINT SSTNTITYRTCTGORYID FOREIGN KEY (ROOTCATEGORYID)
  REFERENCES APP.CM_CATEGORY (ID)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.ASSETENTITYUPLOADABLEBYGROUP
  ADD CONSTRAINT SSTNTTYPLDSSTNTTYD FOREIGN KEY (ASSETENTITYID)
  REFERENCES APP.ASSETENTITY (ID)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.ASSETENTITYUPLOADABLEBYGROUP
  ADD CONSTRAINT SSTNTTYPLDBLSRGRPD FOREIGN KEY (USERGROUPID)
  REFERENCES APP.USERGROUP (ID)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.ATTRIBUTE
  ADD CONSTRAINT ATTRIBUTE_PARENTID FOREIGN KEY (PARENTID)
  REFERENCES APP.ATTRIBUTE (ID)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.ATTRIBUTE
  ADD CONSTRAINT TTRBTETTRBTETYPEID FOREIGN KEY (ATTRIBUTETYPEID)
  REFERENCES APP.ATTRIBUTETYPE (ID)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.ATTRIBUTETYPE
  ADD CONSTRAINT TTRBTTTRBTSTRGTYPD FOREIGN KEY (ATTRIBUTESTORAGETYPEID)
  REFERENCES APP.ATTRIBUTESTORAGETYPE (ID)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.CM_CATEGORY
  ADD CONSTRAINT CMCTGRYXTNSNSSETID FOREIGN KEY (EXTENSIONASSETID)
  REFERENCES APP.ASSET (ID)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.CM_CATEGORY
  ADD CONSTRAINT CMCATEGORYPARENTID FOREIGN KEY (PARENTID)
  REFERENCES APP.CM_CATEGORY (ID)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.CM_CATEGORY
  ADD CONSTRAINT CMCTGRYCTGRYTYPEID FOREIGN KEY (CATEGORYTYPEID)
  REFERENCES APP.CM_CATEGORYTYPE (ID)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.CUSTOMER_ACCOUNT_XREF
  ADD CONSTRAINT CSTMRCCNTXREFCCNTD FOREIGN KEY (ACCOUNT_ID)
  REFERENCES APP.ACCOUNT (ACCOUNT_ID)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.CUSTOMER_ACCOUNT_XREF
  ADD CONSTRAINT CSTMRCCNTXRFCSTMRD FOREIGN KEY (CUSTOMER_ID)
  REFERENCES APP.CUSTOMER (CUSTOMER_ID)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.DIMACCOUNT
  ADD CONSTRAINT DMCCNTPRNTCCUNTKEY FOREIGN KEY (PARENTACCOUNTKEY)
  REFERENCES APP.DIMACCOUNT (ACCOUNTKEY)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.DIMCUSTOMER
  ADD CONSTRAINT DMCSTOMERGGRPHYKEY FOREIGN KEY (GEOGRAPHYKEY)
  REFERENCES APP.DIMGEOGRAPHY (GEOGRAPHYKEY)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.DIMDEPARTMENTGROUP
  ADD CONSTRAINT DMPRNTDPRTMNTGRPKY FOREIGN KEY (PARENTDEPARTMENTGROUPKEY)
  REFERENCES APP.DIMDEPARTMENTGROUP (DEPARTMENTGROUPKEY)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.DIMEMPLOYEE
  ADD CONSTRAINT DMMPLYPRNTMPLYEKEY FOREIGN KEY (PARENTEMPLOYEEKEY)
  REFERENCES APP.DIMEMPLOYEE (EMPLOYEEKEY)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.DIMEMPLOYEE
  ADD CONSTRAINT DMMPLYSLSTRRTRYKEY FOREIGN KEY (SALESTERRITORYKEY)
  REFERENCES APP.DIMSALESTERRITORY (SALESTERRITORYKEY)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.DIMGEOGRAPHY
  ADD CONSTRAINT DMGGRPHSLSTRRTRYKY FOREIGN KEY (SALESTERRITORYKEY)
  REFERENCES APP.DIMSALESTERRITORY (SALESTERRITORYKEY)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.DIMORGANIZATION
  ADD CONSTRAINT DMRGNZTIONCRRNCYKY FOREIGN KEY (CURRENCYKEY)
  REFERENCES APP.DIMCURRENCY (CURRENCYKEY)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.DIMORGANIZATION
  ADD CONSTRAINT DMRGNZPRNTRGNZTNKY FOREIGN KEY (PARENTORGANIZATIONKEY)
  REFERENCES APP.DIMORGANIZATION (ORGANIZATIONKEY)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.DIMPRODUCT
  ADD CONSTRAINT DMPRPRDCTSBCTGRYKY FOREIGN KEY (PRODUCTSUBCATEGORYKEY)
  REFERENCES APP.DIMPRODUCTSUBCATEGORY (PRODUCTSUBCATEGORYKEY)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.DIMPRODUCTSUBCATEGORY
  ADD CONSTRAINT DMPRDCPRDCTCTGRYKY FOREIGN KEY (PRODUCTCATEGORYKEY)
  REFERENCES APP.DIMPRODUCTCATEGORY (PRODUCTCATEGORYKEY)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.DIMRESELLER
  ADD CONSTRAINT DMRSELLERGGRPHYKEY FOREIGN KEY (GEOGRAPHYKEY)
  REFERENCES APP.DIMGEOGRAPHY (GEOGRAPHYKEY)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.FACTCALLCENTER
  ADD CONSTRAINT FCTCALLCENTERDTKEY FOREIGN KEY (DATEKEY)
  REFERENCES APP.DIMDATE (DATEKEY)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.FACTCURRENCYRATE
  ADD CONSTRAINT FCTCRRNCYRCRRNCYKY FOREIGN KEY (CURRENCYKEY)
  REFERENCES APP.DIMCURRENCY (CURRENCYKEY)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.FACTCURRENCYRATE
  ADD CONSTRAINT FCTCRRENCYRATEDTKY FOREIGN KEY (DATEKEY)
  REFERENCES APP.DIMDATE (DATEKEY)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.FACTINTERNETSALES
  ADD CONSTRAINT FCTNTRNTSLCRRNCYKY FOREIGN KEY (CURRENCYKEY)
  REFERENCES APP.DIMCURRENCY (CURRENCYKEY)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.FACTINTERNETSALES
  ADD CONSTRAINT FCTNTRNTSLSCSTMRKY FOREIGN KEY (CUSTOMERKEY)
  REFERENCES APP.DIMCUSTOMER (CUSTOMERKEY)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.FACTINTERNETSALES
  ADD CONSTRAINT FCTNTRNTSLSSHPDTKY FOREIGN KEY (SHIPDATEKEY)
  REFERENCES APP.DIMDATE (DATEKEY)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.FACTINTERNETSALES
  ADD CONSTRAINT FCTNTRNTSLSRDRDTKY FOREIGN KEY (ORDERDATEKEY)
  REFERENCES APP.DIMDATE (DATEKEY)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.FACTINTERNETSALES
  ADD CONSTRAINT FCTNTRNTSALESDDTKY FOREIGN KEY (DUEDATEKEY)
  REFERENCES APP.DIMDATE (DATEKEY)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.FACTINTERNETSALES
  ADD CONSTRAINT FCTNTRNTSLSPRDCTKY FOREIGN KEY (PRODUCTKEY)
  REFERENCES APP.DIMPRODUCT (PRODUCTKEY)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.FACTINTERNETSALES
  ADD CONSTRAINT FCTNTRNTSLSPRMTNKY FOREIGN KEY (PROMOTIONKEY)
  REFERENCES APP.DIMPROMOTION (PROMOTIONKEY)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.FACTINTERNETSALES
  ADD CONSTRAINT FCTNTRNSLSTRRTRYKY FOREIGN KEY (SALESTERRITORYKEY)
  REFERENCES APP.DIMSALESTERRITORY (SALESTERRITORYKEY)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.FACTINTERNETSALESREASON
  ADD CONSTRAINT FCTNTRNTSLSLSRSNKY FOREIGN KEY (SALESREASONKEY)
  REFERENCES APP.DIMSALESREASON (SALESREASONKEY)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.FACTINTERNETSALESREASON
  ADD CONSTRAINT FCTNTRNTSLSRDRNMBR FOREIGN KEY (SALESORDERNUMBER,SALESORDERLINENUMBER)
  REFERENCES APP.FACTINTERNETSALES (SALESORDERNUMBER,SALESORDERLINENUMBER)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.FACTPRODUCTINVENTORY
  ADD CONSTRAINT FCTPRDCTNVNTRYDTKY FOREIGN KEY (DATEKEY)
  REFERENCES APP.DIMDATE (DATEKEY)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.FACTPRODUCTINVENTORY
  ADD CONSTRAINT FCTPRDCTNVNPRDCTKY FOREIGN KEY (PRODUCTKEY)
  REFERENCES APP.DIMPRODUCT (PRODUCTKEY)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.FACTRESELLERSALES
  ADD CONSTRAINT FCTRSLLRSLCRRNCYKY FOREIGN KEY (CURRENCYKEY)
  REFERENCES APP.DIMCURRENCY (CURRENCYKEY)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.FACTRESELLERSALES
  ADD CONSTRAINT FCTRSLLRSLSSHPDTKY FOREIGN KEY (SHIPDATEKEY)
  REFERENCES APP.DIMDATE (DATEKEY)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.FACTRESELLERSALES
  ADD CONSTRAINT FCTRSLLRSALESDDTKY FOREIGN KEY (DUEDATEKEY)
  REFERENCES APP.DIMDATE (DATEKEY)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.FACTRESELLERSALES
  ADD CONSTRAINT FCTRSLLRSLSRDRDTKY FOREIGN KEY (ORDERDATEKEY)
  REFERENCES APP.DIMDATE (DATEKEY)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.FACTRESELLERSALES
  ADD CONSTRAINT FCTRSLLRSLESMPLYKY FOREIGN KEY (EMPLOYEEKEY)
  REFERENCES APP.DIMEMPLOYEE (EMPLOYEEKEY)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.FACTRESELLERSALES
  ADD CONSTRAINT FCTRSLLRSLSPRDCTKY FOREIGN KEY (PRODUCTKEY)
  REFERENCES APP.DIMPRODUCT (PRODUCTKEY)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.FACTRESELLERSALES
  ADD CONSTRAINT FCTRSLLRSLSPRMTNKY FOREIGN KEY (PROMOTIONKEY)
  REFERENCES APP.DIMPROMOTION (PROMOTIONKEY)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.FACTRESELLERSALES
  ADD CONSTRAINT FCTRSLLRSLSRSLLRKY FOREIGN KEY (RESELLERKEY)
  REFERENCES APP.DIMRESELLER (RESELLERKEY)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.FACTRESELLERSALES
  ADD CONSTRAINT FCTRSLLSLSTRRTRYKY FOREIGN KEY (SALESTERRITORYKEY)
  REFERENCES APP.DIMSALESTERRITORY (SALESTERRITORYKEY)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.FACTSALESQUOTA
  ADD CONSTRAINT FCTSALESQUOTADTKEY FOREIGN KEY (DATEKEY)
  REFERENCES APP.DIMDATE (DATEKEY)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.FACTSALESQUOTA
  ADD CONSTRAINT FCTSLSQUOTAMPLYKEY FOREIGN KEY (EMPLOYEEKEY)
  REFERENCES APP.DIMEMPLOYEE (EMPLOYEEKEY)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.FACTSURVEYRESPONSE
  ADD CONSTRAINT FCTSRVYRSPNCSTMRKY FOREIGN KEY (CUSTOMERKEY)
  REFERENCES APP.DIMCUSTOMER (CUSTOMERKEY)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.FACTSURVEYRESPONSE
  ADD CONSTRAINT FCTSRVYRSPONSEDTKY FOREIGN KEY (DATEKEY)
  REFERENCES APP.DIMDATE (DATEKEY)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.FILEFORMAT
  ADD CONSTRAINT FLFORMATSSETTYPEID FOREIGN KEY (ASSETTYPEID)
  REFERENCES APP.ASSETTYPE (ID)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.INDESIGNLINKEDRESOURCE
  ADD CONSTRAINT NDSGNLNKDRSRCESSTD FOREIGN KEY (ASSETID)
  REFERENCES APP.ASSET (ID)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.INDESIGNLINKEDRESOURCE
  ADD CONSTRAINT NDSGNLNKDRLNKDSSTD FOREIGN KEY (LINKEDASSETID)
  REFERENCES APP.ASSET (ID)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.MENUITEMHIDDENFROMGROUP
  ADD CONSTRAINT MNTMHDDNFMNTMDNTFR FOREIGN KEY (MENUITEMIDENTIFIER)
  REFERENCES APP.MENUITEM (ITEMIDENTIFIER)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.MENUITEMHIDDENFROMGROUP
  ADD CONSTRAINT MNTMHDDNFRMGSRGRPD FOREIGN KEY (USERGROUPID)
  REFERENCES APP.USERGROUP (ID)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.ORGUNIT
  ADD CONSTRAINT RGNTRTRGNTCTGORYID FOREIGN KEY (ROOTORGUNITCATEGORYID)
  REFERENCES APP.CM_CATEGORY (ID)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.ORGUNIT
  ADD CONSTRAINT RGNRTDSCRPTVCTGRYD FOREIGN KEY (ROOTDESCRIPTIVECATEGORYID)
  REFERENCES APP.CM_CATEGORY (ID)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.ORGUNIT
  ADD CONSTRAINT RGUNITADMINGROUPID FOREIGN KEY (ADMINGROUPID)
  REFERENCES APP.USERGROUP (ID)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.ORGUNIT
  ADD CONSTRAINT RGNTSTNDARDGROUPID FOREIGN KEY (STANDARDGROUPID)
  REFERENCES APP.USERGROUP (ID)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.ORGUNITGROUP
  ADD CONSTRAINT RGNITGROUPRGUNITID FOREIGN KEY (ORGUNITID)
  REFERENCES APP.ORGUNIT (ID)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.ORGUNITGROUP
  ADD CONSTRAINT RGNTGROUPSRGROUPID FOREIGN KEY (USERGROUPID)
  REFERENCES APP.USERGROUP (ID)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.REGION
  ADD CONSTRAINT REGION_COUNTRYID FOREIGN KEY (COUNTRYID)
  REFERENCES APP.COUNTRY (ID)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.USEREDITLANGUAGE
  ADD CONSTRAINT SREDITLANGUAGESRID FOREIGN KEY (USERID)
  REFERENCES APP.ASSETBANKUSER (ID)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.USEREDITLANGUAGE
  ADD CONSTRAINT SRDTLANGUAGELNGGID FOREIGN KEY (LANGUAGEID)
  REFERENCES APP.LANGUAGE (ID)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.USERGROUP
  ADD CONSTRAINT USERGROUP_BRANDID FOREIGN KEY (BRANDID)
  REFERENCES APP.BRAND (ID)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.USERGROUP
  ADD CONSTRAINT SRGRPHMPGMNTMDNTFR FOREIGN KEY (HOMEPAGEMENUITEMIDENTIFIER)
  REFERENCES APP.MENUITEM (ITEMIDENTIFIER)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.USERINGROUP
  ADD CONSTRAINT USERINGROUP_USERID FOREIGN KEY (USERID)
  REFERENCES APP.ASSETBANKUSER (ID)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;

ALTER TABLE APP.USERINGROUP
  ADD CONSTRAINT SRINGROUPSRGROUPID FOREIGN KEY (USERGROUPID)
  REFERENCES APP.USERGROUP (ID)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;


COMMIT;
